### ISSUE TITLE
area.dat (deleted) overrideen just by last new entry

### ISSUE THREAD

**Issue by ghost** [minetest-mods/areas#34]
hello
the area.dat file is maybe (deleted) but I think more like overridden just by last new entry made from a gamer with /protect ... .

I didn't change anything at file , it worked well, but since about one week ago,
and today I see live that this happen just after a new entry had been made.

Is there a limit in size ? 78.6 kb
entries ?
or if someone own an area (player) is deleted by the [mod] minetest_cleaner ?

**Comment by SmallJoker** [comment]
Maybe fixed by #47. Please re-open a new issue if this still occurs.

**Comment by mckaygerhard** [comment]
hi .. this #47 solves but now.. what happend if i migrated from older version of areas to a nwer with this commits included? @SmallJoker ?
