### ISSUE TITLE
playerfaction sharing is lost on logging out

### ISSUE THREAD

**Issue by int-ua** [minetest-mods/areas#39]
Steps to reproduce: 
Do `/area_faction_open <ID>`, log out, log back in.

Expected:
Open status is saved

Current:
Area is not open after logging back in.

#37

**Comment by crabctrl** [comment]
I'm not sure what's causing this, I'll take a look

**Comment by crabctrl** [comment]
Sorry it took so long for me to get around to this; it's an issue with the `playerfactions` mod itself, not `areas`. I'll try to push a fix in the next couple of days. Also wanted to mention that said mod has been moved [here](https://git.leagueh.xyz/katp32/playerfactions) due to a name change.

**Comment by crabctrl** [comment]
`playerfactions` has now been patched to fix this; this issue can be closed

**Comment by BobFred7** [comment]
@int-ua :arrow_up:
