### ISSUE TITLE
/list_areas creates a long list that scrolls off the chat buffer

### ISSUE THREAD

**Issue by Billre** [minetest-mods/areas#40]
As an admin, using the /list_areas command will give me a long list of all the areas on the server, which, after a certain number of areas, will scroll off the chat buffer, leaving me unable to get information on those areas.   I would like an option to add an area number or range of areas, like /list_areas 25-74 or /list_areas 98.

**Comment by SmallJoker** [comment]
A PR to scroll through and filter by area name is welcome. I don't think it's handy to only use chat commands.

**Comment by mckaygerhard** [comment]
related to #51 .. the solution is to truncate but given the first areas.. and the number of areas protected.. the admin must know the amount of areas in protection.. 

of course the right way solution is to use the mod named  https://bitbucket.org/sorcerykid/formspecs active form spec !

**Comment by mckaygerhard** [comment]
the mod factions cut list when are so long.. as https://github.com/mt-mods/playerfactions/commit/0b799f3c5f3a683bffd4dca745156025728f9e9c
