### ISSUE TITLE
[Question] Is protecting super large areas safe?

### ISSUE THREAD

**Issue by debagos** [minetest-mods/areas#55]
I want to protect a very large tunnel, over 7k nodes long.
Will protecting such a huge area impact the performance or even crash the server?

**Comment by SmallJoker** [comment]
@debagos Area dimensions do not matter. The intersection calculations are the same depend on the area count, but not the sizes.

**Comment by debagos** [comment]
Ah, thank you very much for clearing that up. :+1:
