### ISSUE TITLE
AREAS deletable by anyone

### ISSUE THREAD

**Issue by nininik0** [minetest-mods/areas#76]
Using remove areas or recrusive remove areas, it dosent require privileges which is why a player on my server greifed spawn and deleted all areas. 
I suggest setting a privilege to do that. As the player that did it only had fast and the default privellges.

**Comment by Niklp09** [comment]
This isn't true, [`areas:isAreaOwner()` checks for the areas admin priv](https://github.com/minetest-mods/areas/blob/9a5cdb282251ad18ead934d0cb12a7293a379384/internal.lua#L328-L344).
