### ISSUE TITLE
/list_areas returns <invalid multibyte string>

### ISSUE THREAD

**Issue by Megaf** [minetest-mods/areas#9]
https://github.com/ShadowNinja/areas/commit/3f777900d45fba0b2e64791c40421df623d25c5a#commitcomment-9040424

**Comment by ShadowNinja** [comment]
This looks like an engine issue.  Try with a gettext build.

**Comment by Megaf** [comment]
It happens with gettext enabled too. Tested on a clean clone from master.

**Comment by Megaf** [comment]
So, any idea on what could the cause be?
And, where are the areas stored? I'm thinking about doing a fresh git clone of areas.

**Comment by ShadowNinja** [comment]
1. Someone added an area with a name that contains bytes that are invalid when decoded with your systems default encoding,
2. Wherever `areas.filename` points to.  It's `areas.dat` in your world directory by default.

**Comment by SmallJoker** [comment]
Possibly fixed in the Minetest Engine. Now we're facing #51.
